apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-login
  labels:
    app: nginx-login
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-login
  template:
    metadata:
      labels:
        app: nginx-login
    spec:
      nodeSelector:
        disktype: worker1  # 노드 셀렉터
      containers:
      - name: nginx
        image: kku9/nginx-login:v1.40  # 이미지 위치 수정
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "100m"
            memory: "128Mi"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 120
          periodSeconds: 60
          timeoutSeconds: 10
          failureThreshold: 5
          successThreshold: 1

---
apiVersion: v1
kind: Service
metadata:
  name: svc-login
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30200
    protocol: TCP
  selector:
    app: nginx-login
