apiVersion: apps/v1
kind: Deployment
metadata:
  name: myhomegym-main
  labels:
    app: myhomegym-main
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myhomegym-main
  template:
    metadata:
      labels:
        app: myhomegym-main
    spec:
      containers:
      - image: kku9/nginx-web:v1.21
        name: web
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "250m"
            memory: "250Mi"
          limits:
            cpu: "250m"
            memory: "250Mi"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 15
          timeoutSeconds: 5
          failureThreshold: 3
          successThreshold: 1
---
apiVersion: v1
kind: Service
metadata:
  name: svc-main
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30100
  selector:
    app: myhomegym-main
