apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-main
  labels:
    app: tomcat-main
spec:
  progressDeadlineSeconds: 600
  revisionHistoryLimit: 10
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  replicas: 3
  selector:
    matchLabels:
      app: tomcat-main
  template:
    metadata:
      labels:
        app: tomcat-main
    spec:
      nodeSelector:
        disktype: worker3  # 노드 셀렉터
      containers:
      - name: was
        image: kku9/was-sure:9
        volumeMounts:
        - name: data
          mountPath: /usr/share/nginx/html
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "250m"
            memory: "300Mi"
          limits:
            cpu: "250m"
            memory: "300Mi"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 120
          periodSeconds: 60
          timeoutSeconds: 10
          failureThreshold: 5
          successThreshold: 1
        volumes:
        - name: data
          hostPath:
            type: FileOnCreate
            path: /web

---
apiVersion: v1
kind: Service
metadata:
  name: svc-was-main
spec:
  type: ClusterIP
  clusterIP: 10.110.0.100
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: tomcat-main
